"""init

Revision ID: 1df73be2338f
Revises: 9a7a370c2417
Create Date: 2023-12-17 06:41:52.599329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1df73be2338f'
down_revision: Union[str, None] = '9a7a370c2417'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('first_name', sa.String(length=150), nullable=False))
    op.add_column('contacts', sa.Column('extra_data', sa.String(length=150), nullable=False))
    op.drop_column('contacts', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.drop_column('contacts', 'extra_data')
    op.drop_column('contacts', 'first_name')
    # ### end Alembic commands ###
